@startuml

title __DATABASE's Class Diagram__\n

  namespace com.example.fitnesstracker {
    namespace Database {
      class com.example.fitnesstracker.Database.DatabaseHelper {
          {static} + COLUMN_EXERCISE_DESC : String
          {static} + COLUMN_EXERCISE_ID : String
          {static} + COLUMN_EXERCISE_KG : String
          {static} + COLUMN_EXERCISE_NAME : String
          {static} + COLUMN_EXERCISE_REPS : String
          {static} + COLUMN_EXERCISE_URL : String
          {static} + COLUMN_SAVED_WORKOUTS_EXERCISE_ID : String
          {static} + COLUMN_SAVED_WORKOUTS_ID : String
          {static} + COLUMN_SAVED_WORKOUTS_WORKOUT_ID : String
          {static} + COLUMN_WORKOUT_ID : String
          {static} + COLUMN_WORKOUT_NAME : String
          {static} + COLUMN_WORKOUT_ROUURINES_DATE : String
          {static} + COLUMN_WORKOUT_ROUURINES_EXERCISE_ID : String
          {static} + COLUMN_WORKOUT_ROUURINES_ID : String
          {static} + COLUMN_WORKOUT_ROUURINES_REPS_EXECUTED : String
          {static} + COLUMN_WORKOUT_ROUURINES_TIME_TAKEN : String
          {static} + COLUMN_WORKOUT_ROUURINES_WORKOUT_ID : String
          {static} + DATABASE_NAME : String
          {static} + DATABASE_VERSION : int
          {static} + SQL_CREATE_TABLE_EXERCISES : String
          {static} + SQL_CREATE_TABLE_SAVED_WORKOUTS : String
          {static} + SQL_CREATE_TABLE_WORKOUTS : String
          {static} + SQL_CREATE_TABLE_WORKOUT_ROUTINES : String
          {static} + TABLE_EXERCISES : String
          {static} + TABLE_SAVED_WORKOUTS : String
          {static} + TABLE_WORKOUT : String
          {static} + TABLE_WORKOUT_ROUURINES : String
          {static} + TAG : String
          + DatabaseHelper()
          + dropExercise()
          + dropWorkout()
          + getExerciseData()
          + getExerciseRoutineData()
          + getExerciseRow()
          + getExerciseRow()
          + getSavedExerciseData()
          + getWorkoutData()
          + getWorkoutRow()
          + getWorkoutRow()
          + insertExerciseData()
          + insertExerciseRoutineData()
          + insertRecordedWorkout()
          + insertWorkoutData()
          + onConfigure()
          + onCreate()
          + onUpgrade()
          + updateExerciseRow()
          + updateWorkoutRow()
      }
    }
  }
  

  com.example.fitnesstracker.Database.DatabaseHelper -up-|> android.database.sqlite.SQLiteOpenHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
